# Generated by Django 4.2 on 2024-10-17 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='the start must be greater than today',
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 10, 17)),
        ),
    ]
